import { helpSections } from "@/lib/helpContent.ko";

export const uiTextKo = {
  app: {
    title: "MMD",
    description: "개인용 금융 비교, 추천, 플래닝을 위한 로컬 우선 서비스",
    brand: "MMD",
  },
  nav: {
    home: "홈",
    deposit: "예금",
    saving: "적금",
    recommend: "추천",
    planner: "플래닝",
    help: "도움말",
  },
  home: {
    heading: "개인 금융 의사결정을 빠르게 정리하세요",
    subtitle:
      "예금·적금 비교, 프로필 기반 추천, 간단 플래닝을 한 화면 흐름으로 점검할 수 있습니다.",
    cards: [
      { href: "/products/deposit", title: "예금 상품 보기", desc: "최고금리와 기간별 옵션 확인" },
      { href: "/products/saving", title: "적금 상품 보기", desc: "적립 방식과 우대금리 비교" },
      { href: "/recommend", title: "추천 보기", desc: "점수 근거가 보이는 맞춤 추천" },
      { href: "/planning", title: "플래닝 보기", desc: "저축률과 목표 달성 시뮬레이션" },
      { href: "/help", title: "도움말", desc: "사용법, 계산 가정, 데이터 모드 안내" },
    ],
  },
  help: {
    title: "도움말",
    subtitle: "앱 사용법과 계산 가정을 확인하세요.",
    close: "닫기",
    open: "도움말",
    sections: helpSections,
  },
  product: {
    mockNotice: "키가 없어도 모의 데이터로 확인할 수 있습니다.",
    filterLabel: "금융권역 코드",
    query: "조회",
    modeLabel: "데이터 모드",
    fallbackMessage: "실데이터 실패 후 모의 데이터 전환",
    bestRate: "최고금리",
    bestTerm: "대표기간",
    optionsCount: "옵션",
    optionSummary: "옵션 보기",
    optionHint: "옵션은 같은 상품의 기간·조건별 금리 항목입니다.",
    optionTerm: "기간(개월)",
    optionRate: "기본금리(%)",
    optionMaxRate: "최고금리(%)",
    optionRateType: "금리유형",
    optionReserveType: "적립유형",
  },
  recommend: {
    scoreLabel: "최종점수",
    dataMode: "데이터 모드",
    calc: "추천 계산",
    contribRate: "금리 점수",
    contribTerm: "기간 적합도",
    contribLiq: "유동성 적합도",
    weights: "가중치",
    maxPointsLabel: "100점 만점",
    breakdownLabel: "점수 구성",
    pickedOptionLabel: "대표옵션",
    scoreHelpTitle: "점수 설명 (0~100점)",
    scoreHelpBody: [
      "점수는 현재 후보군 내 상대 비교 결과이며, 상품 절대평가 점수가 아닙니다.",
      "금리 점수: 후보군의 대표금리를 최소~최대 범위로 정규화해 반영합니다.",
      "기간 적합도: 선호기간과 대표옵션 기간 차이가 작을수록 높은 점수를 받습니다.",
      "유동성 적합도: 유동성 선호(높음/보통/낮음)와 기간 일치도에 따라 점수를 부여합니다.",
      "가중치는 금리 선호 성향에 따라 달라지며, 확정 수익을 의미하지 않습니다.",
    ],
  },
  planner: {
    title: "5단계 플래닝(초안)",
    subtitle:
      "목표 설정 → 상태 분석 → 대안 제시 → 실행 → 모니터링 순서로 자동 초안을 생성합니다. 모든 결과는 가정 기반이며 보험·세금·연금·자산배분은 단계적으로 확장됩니다.",
    stepGoal: "목표 설정",
    stepAnalysis: "상태 분석",
    stepAlternatives: "대안 제시",
    stepExecution: "실행",
    stepMonitoring: "모니터링",
    sectionExecution: "실행 체크리스트",
    sectionMonitoring: "모니터링 루틴",
    cardWhy: "왜",
    cardActions: "지금 할 일",
    cardAssumptions: "사용한 가정",
    cardCaution: "주의",
  },
} as const;
