import { NewsSourceSchema, type NewsSource } from "./contracts";

const rawSources: NewsSource[] = [
  {
    id: "bok_press_all",
    name: "한국은행 보도자료(전체)",
    feedUrl: "https://www.bok.or.kr/portal/bbs/B0000552/news.rss?menuNo=200690",
    homepageUrl: "https://www.bok.or.kr/",
    country: "KR",
    language: "ko",
    weight: 1.2,
    enabled: true,
  },
  {
    id: "bok_mpc_decisions",
    name: "한국은행 금통위 의결사항",
    feedUrl: "https://www.bok.or.kr/portal/bbs/P0000093/news.rss?menuNo=200761",
    homepageUrl: "https://www.bok.or.kr/",
    country: "KR",
    language: "ko",
    weight: 1.4,
    enabled: true,
  },
  {
    id: "kosis_monthly_trend",
    name: "KOSIS 주요 월간동향",
    feedUrl: "https://kosis.kr/rss/trend_rss.jsp",
    homepageUrl: "https://kosis.kr/",
    country: "KR",
    language: "ko",
    weight: 1.1,
    enabled: true,
  },
  {
    id: "kostat_press",
    name: "통계청 보도자료(KOSIS RSS)",
    feedUrl: "http://kostat.go.kr/menu.es?mid=a10301010000&act=rss",
    homepageUrl: "https://kostat.go.kr/",
    country: "KR",
    language: "ko",
    weight: 1.2,
    enabled: true,
  },
  {
    id: "moef_econ_policy_en",
    name: "MOEF Economic Policy (EN RSS)",
    feedUrl: "http://english.moef.go.kr/ec/engmosfpolicyrss.do?boardCd=E0005",
    homepageUrl: "https://english.moef.go.kr/",
    country: "KR",
    language: "en",
    weight: 1.0,
    enabled: true,
  },
  {
    id: "fed_press_all",
    name: "Federal Reserve - All Press Releases (RSS)",
    feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
    homepageUrl: "https://www.federalreserve.gov/",
    country: "US",
    language: "en",
    weight: 1.1,
    enabled: false,
  },
  {
    id: "bis_press",
    name: "BIS - Press releases (RSS)",
    feedUrl: "https://www.bis.org/doclist/all_pressrels.rss",
    homepageUrl: "https://www.bis.org/",
    country: "CH",
    language: "en",
    weight: 1.0,
    enabled: false,
  },
  {
    id: "ecb_press",
    name: "ECB - Press releases/speeches (RSS entry point)",
    feedUrl: "https://www.ecb.europa.eu/home/html/rss.en.html",
    homepageUrl: "https://www.ecb.europa.eu/",
    country: "EU",
    language: "en",
    weight: 1.0,
    enabled: false,
  },
];

export const NEWS_SOURCES: NewsSource[] = rawSources.map((source) => NewsSourceSchema.parse(source));
